Real <a> tags in admin menu
luyadev/luya-module-admin pull request #665
Opened 2021-09-24 11:31 UTC by Antikon

### What are you changing/introducing
Replaced <span> tags with <a> tags in main admin menu and submenus.

### What is the reason for changing/introducing
A сapability to use middle-clicking, right-clicking, and ctrl-clicking on the menu item.

### QA

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #451

2021-09-25 06:37 UTC, nadar requested changes
In terms of code this looks good to me, the changelog is missing. @TheMaaarc i assume this should not make a problem in design as the css code is not referring to the element instead the class has precedence, right?

2021-09-27 18:32 UTC, TheMaaarc approved these changes
Looks good to me. 👍

2021-09-27 18:33 UTC, nadar approved these changes

2021-09-27 18:34 UTC, merged

2021-09-28 21:11 UTC, hbugdoll commented
Accessibility is also improved 👍