zaaCheckboxArray: added toggleAll button.
luyadev/luya-module-admin pull request #723
Opened 2022-06-07 23:12 UTC by chemezov

### What are you changing/introducing

Hi there! I've added "toggle all" button to zaaCheckboxArray plugin. How it looks like:

![image](https://user-images.githubusercontent.com/2368902/172497932-134f7998-37a3-4707-9205-3d86bcc4612c.png)

1) I'm not sure I added the styles to the right files.
2) How can i build resources and compile main.css file?
3) What do you think about this?

### What is the reason for changing/introducing

Some of the lists are quite long. And there is a need to select all but a few.

### QA

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes/no
| Fixed issues  |

2022-06-09 09:16 UTC, TheMaaarc requested changes
Thanks!

2022-06-09 09:16 UTC, TheMaaarc commented on src/resources/js/formdirectives.js
> +                        '<button ng-click="toggleAll()" type="button" class="ckeckbox-list-toggle-button btn btn-info btn-icon"><i class="material-icons">done_all</i></button>' +
Rename `checkbox-list-toggle-button` to `zaa-checkbox-array-toggle-all`, we already have a `zaa-checkbox-array.scss` file which defines some `zaaCheckboxArray` spcific things.

2022-06-09 09:16 UTC, TheMaaarc commented on src/resources/scss/admin.scss
> +@import "components/checkbox-toggle-button";
Remove `checkbox-toggle-button` entry and file, move code to end of  `components/_zaa-checkbox-array.scss`.

2022-06-09 09:16 UTC, TheMaaarc commented on src/resources/scss/components/_checkbox-list-toggle-button.scss
> +.ckeckbox-list-toggle-button {
Rename to `.zaa-checkbox-array-toggle-all`.

2022-06-09 09:16 UTC, TheMaaarc commented on src/resources/scss/components/_checkbox-list-toggle-button.scss
> +.ckeckbox-list-toggle-button + luya-checkbox-array {
Rename to `.zaa-checkbox-array-toggle-all + luya-checkbox-array`.

2022-06-09 13:18 UTC, chemezov commented
@TheMaaarc Thank you very much for the detailed review, much appreciated. All things done.

2022-06-14 09:07 UTC, chemezov commented
So, there is last questions:
1) Resources: How can i build resources and compile main.css file?
2) Tooltip: How can i add i18n for tooltip?
3) What to do with tests? I have very little experience with this.

2022-06-14 13:11 UTC, nadar commented
> Resources: How can i build resources and compile main.css file?
We will do that for you before release

> Tooltip: How can i add i18n for tooltip?
Is this related to that PR? There are tooltip directives which works with i18n text. Please create a forum entry so we can explain

> What to do with tests? I have very little experience with this.
Not that much of js tests sadly.

2022-06-15 10:50 UTC, chemezov commented
Done fixes and added changelog entry. If tooltip is not necessary, this task is done completely.

2022-06-15 11:12 UTC, nadar commented
> If tooltip is not necessary

I think thats ok like that :+1:

2022-06-15 11:12 UTC, nadar approved these changes

2022-06-15 11:12 UTC, merged